version: "3.8"

services:
  openvpn:
    build:
      dockerfile: Dockerfile
    container_name: openvpn
    environment:
      - PKI_PASSWORD=${PKI_PASSWORD} # Set this variable in your .env file or the environment
      - BBOLT_CLIENT_STORE_PATH=${BBOLT_CLIENT_STORE_PATH}
      - M2M_AUTH_TOKEN=${M2M_AUTH_TOKEN}
    volumes:
      - openvpn-data:/etc/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  openvpn-data:
    external: true
