version: '3.8'

services:
  openvpn:
    image: rolo-openvpn
    container_name: openvpn
    environment:
      - PKI_PASSWORD=${PKI_PASSWORD} # Set this variable in your .env file or the environment
    volumes:
      - ovpn_data:/etc/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  openvpn_data:
    external: true
